# Cargo.toml
[package]
name = "dtree"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28"
crossterm = "0.28"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
arboard = "3.4"
unicode-width = "0.1"
unicode-truncate = "1.1"